### ISSUE TITLE
Compile-time dependency exception

### ISSUE THREAD

**Issue by MarkLi2011** [longsleep/realtimetraffic#2] opened 2017-09-28 09:13 UTC
[root@fs_01 realtimetraffic-master]# make
if [ -z "" ]; then GOPATH="/home/gofile/src/test/realtimetraffic-master/vendor:/home/gofile/src/test/realtimetraffic-master" go get github.com/rogpeppe/godeps; fi
if [ -z "" ]; then GOPATH="/home/gofile/src/test/realtimetraffic-master/vendor:/home/gofile/src/test/realtimetraffic-master" /home/gofile/src/test/realtimetraffic-master/vendor/bin/godeps -u dependencies.tsv; fi
/bin/sh: /home/gofile/src/test/realtimetraffic-master/vendor/bin/godeps: Do not have that file or directory
make: *** [goget] error 127

thanks！！！

**Comment by MarkLi2011** [comment] 2017-09-28 09:31
It should be necessary to manually compile some dependencies

**Comment by MarkLi2011** [comment] 2017-09-28 09:41
The problem has been solved

Need to manually compile go-bindata, godeps dependencies and copy to the appropriate directory, note that the compiler-dependent package (vet) address changes:
package old address: golang.org/x/tools/cmd/vet
package new address: github.com/golang/go/src/cmd/vet

Otherwise there will be the following error:
`package golang.org/x/tools/cmd/vet: unrecognized import path "golang.org/x/tools/cmd/vet" (https fetch: Get https://golang.org/x/tools/cmd/vet go-get = 1: dial tcp 216.239.37.1:443: i / o timeout)
make [1]: *** [vet] error 1`

**Comment by longsleep** [comment] 2017-09-28 09:45
Thanks for pointing this out. `make` should get godeps automatically. Might move the project to glide as a solution.

**Comment by MarkLi2011** [comment] 2017-09-28 10:12
Thank you for sharing, I was manually resolved, not familiar with makefile and golang

**Comment by MarkLi2011** [comment] 2017-09-28 10:30
It does not seem to be a collection of data

![image](https://user-images.githubusercontent.com/9192780/30962098-07fadace-a47b-11e7-916a-850e3dc39d5d.png)

**Comment by longsleep** [comment] 2017-10-13 17:05
Closing, cannot reproduce the initial issue. Godeps works fine.

**Closed as completed by longsleep** 2017-10-13 17:05 UTC
Labels: Hacktoberfest
